// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSlV-6Iz-JZwmBy5YkWgA1c_iqt3L0S8k',
    appId: '1:916713107635:web:1e969d41d49ccf6aae80c6',
    messagingSenderId: '916713107635',
    projectId: 'appconferencia-c6875',
    authDomain: 'appconferencia-c6875.firebaseapp.com',
    storageBucket: 'appconferencia-c6875.appspot.com',
    measurementId: 'G-B5CK1VF2LQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMJ8cwxZuggPHDZ5LnRxqdbHTxyKQN8ao',
    appId: '1:916713107635:android:9447da2e5f0e9d28ae80c6',
    messagingSenderId: '916713107635',
    projectId: 'appconferencia-c6875',
    storageBucket: 'appconferencia-c6875.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU27hKLfxIUiH_pQTC8r3T5Yb2KhryauA',
    appId: '1:916713107635:ios:bd5ddf5d8a9b206dae80c6',
    messagingSenderId: '916713107635',
    projectId: 'appconferencia-c6875',
    storageBucket: 'appconferencia-c6875.appspot.com',
    iosClientId: '916713107635-s1m8bu0d8e0s152bo1d3ukfonmchjt8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.appconferencia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU27hKLfxIUiH_pQTC8r3T5Yb2KhryauA',
    appId: '1:916713107635:ios:bd5ddf5d8a9b206dae80c6',
    messagingSenderId: '916713107635',
    projectId: 'appconferencia-c6875',
    storageBucket: 'appconferencia-c6875.appspot.com',
    iosClientId: '916713107635-s1m8bu0d8e0s152bo1d3ukfonmchjt8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.appconferencia',
  );
}
